### ISSUE TITLE
How to apply mongoose

### ISSUE THREAD

**Issue by imsergiobernal** [jbuget/nodejs-clean-architecture-app#1]
Hello @jbuget I think that this example is the most clear one but, I'm having difficulties about adding mongoose properly.

I think it would be useful if we expand this example in another branch with a mongoose or ODM example.

**Comment by edarcarto** [comment]
> Hello @jbuget I think that this example is the most clear one but, I'm having difficulties about adding mongoose properly.
> 
> I think it would be useful if we expand this example in another branch with a mongoose or ODM example.

The possible solution is:
--------------------------
Create a plugin with the connection string in mongoose and then import in server.js.
Change in controller ModelRepostoryInMemory for ModelRepository and then in database create a moongose model and in the persist function into ModelRepository this:

`const row = Object.assign ({}, userEntity);
return this.user.create (row);`

**Comment by imsergiobernal** [comment]
Thanks a lot @edarcarto should I storage models and schemas in domain level?

**Comment by xaeli** [comment]
> Hello @jbuget I think that this example is the most clear one but, I'm having difficulties about adding mongoose properly.
> 
> I think it would be useful if we expand this example in another branch with a mongoose or ODM example.

Hi I just found this video: https://www.youtube.com/watch?v=CnailTcJV_U
It uses mongoose and a lot of nice patterns, I hope you could find it useful

**Comment by jbuget** [comment]
Hello @imsergiobernal. Sorry for the very late answer. I recently made an example of a repository that connects and use a SQL database (SQLite3). You can have a look at [lib/interface_adapters/storage/UserRepositorySQLite.js](https://github.com/jbuget/nodejs-clean-architecture-app/blob/master/lib/interface_adapters/storage/UserRepositorySQLite.js).
