### ISSUE TITLE
Could you go into more detail about the user repository?

### ISSUE THREAD

**Issue by fishnibble** [jbuget/nodejs-clean-architecture-app#4]
I do not understand this class and what it is used for. I kept looking for the repository pattern online, but after reading a few write ups I feel more confused on the topic.

**Comment by jbuget** [comment]
In my view, a repository is just an Entity Collection manager. 

I dissociate the fact to fetch or save data and the fact to treat and manipulate this data. To me, only the second concern (data manipulation) is part a real part of the "business domain level". I consider the first one as a system-level implementation detail.

It is why I don't like to find CRUD methods in domain entities.
