### ISSUE TITLE
Proposal: use inheritance instead of composition for the repository pattern

### ISSUE THREAD

**Issue by sroccaserra** [jbuget/nodejs-clean-architecture-app#5]
I think having chosen composition for the repository pattern is a problem here:

**UserRepository.js**
```js
class UserRepository {
  constructor(repository) {
    this.repository = repository;
  }

  persist(userEntity) {
    return this.repository.persist(userEntity);
  }

  // ...

}
```

**UserInMemoryRepository.js**
```js
// Nothing to see here, no explicit dependency :(
```

**UserController.js**
```js
  // ...
  const userRepository = new UserRepository(new UserRepositoryInMemory());
  //...
```

It has at least three inconvenients:
- having to explicitely delegate every method call to `this.repository`
- breaking the plugin architecture (here a change in the outer circle code would require to change the inner circle code)
- having no explicit dependency to the `UserRepository` class in the in memory & sqlite implementations

----

I propose to use inheritance instead:

**UserRepository.js**
```js
class UserRepository {
  persist(userEntity) {
    // This optional generic implementation is obviously meant to be overriden.
    // See also Python's NotImplementedError and Smalltalk's subclassResponsibility.
    throw new Error('ERR_METHOD_NOT_IMPLEMENTED');
  }

  // ...

}
```

```js
// Explicit dependency here :)
const UserRepository = require('../path/to/UserRepository')

class UserRepositoryInMemory extends UserRepository {
  persist(userEntity) {
    // Real implementation here
    // ...
  }
}
```

**UserController.js**
```js
  // This initiation could be done in a composition root,
  // which would be the only place where things could get a little dirty ;)
  const userRepository = new UserRepositoryInMemory();
  
  // ...
```

**Comment by sroccaserra** [comment]
About composition roots:
- https://blog.ploeh.dk/2011/07/28/CompositionRoot/

**Comment by sroccaserra** [comment]
Illustrated in PR #6.

Note: even better, make `UserRepository` a real interface (requires to use a JS static type system like TypeScript). But this is another topic.

Cheers!
Sébastien.

**Comment by jbuget** [comment]
Change accepted and merged (thanks @sroccaserra ) 👌

**Comment by jbuget** [comment]
Change accepted and merged (thanks @sroccaserra ) 👌
