### ISSUE TITLE
Interface UserRepositorySQLite.js depends on sequelize (frameworks_drivers)

### ISSUE THREAD

**Issue by rmallermartins** [jbuget/nodejs-clean-architecture-app#7]
Isn't that a decency from an inner layer (interface_adapters) to an outer layer (frameworks_drivers)?

```javascript
// UserRepositorySQLite.js

const sequelize = require('../../frameworks_drivers/database/sequelize');
```

Couldn't get myself to a way of inverting this dependency, but would be grateful if anyone does :)

**Comment by davidsierradz** [comment]
To help get a clearer picture of the dependencies I used [pahen/madge](https://github.com/pahen/madge) to visualize the module's graph:

![graph-sql](https://user-images.githubusercontent.com/9190258/72283753-69756f00-360d-11ea-8704-a4b7174f02b0.png)
