### ISSUE TITLE
Domain Services

### ISSUE THREAD

**Issue by jerolan** [jbuget/nodejs-clean-architecture-app#8]
What is `services` in `enterprise_business_rules` (`UpdateAnalytics.js`)?

**Comment by jbuget** [comment]
In my view, there are multiple level of services. I used to make services when I definitely can not decide which entity or aggregate is the most responsible of a given treatment or intent. But I don't like them. I think that this kind of situation is a _bad smell_. Maybe I am manipulating a given concept, adapted and forecast for a specific context, into another one.

**Comment by jbuget** [comment]
After thinking, domain services were too complicated and overall useless. So I removed the empty package.
